from collections import defaultdict

FOOD_COLOR = "#00BB00"
POISON_COLOR = "#BB0000"
TARGET_COLOR = "#FFFF66"
VEH_ALIVE = '#00FF00'
VEH_DEAD = '#FF0000'
NUM_OF_FOOD = 20
NUM_OF_POISON = 20

NUM_OF_VEHICLES = 10
DEFAULT_R = 4
VEH_SIZE = DEFAULT_R * 3
CANVAS_WIDTH = 1000  # 700
CANVAS_HEIGHT = 1050  # 750
MAX_SPEED = 6
FORCE_COEFFICIENT = 0.07
HP_DEC_PER_FRAME = -0.005


LIMITS = {
    "RADIUS": CANVAS_WIDTH/2,
    "ACC_MUL": 5,
    "DIST_POW": 2
}

EDIBLE = {
    "FOOD": 0.4,
    "POISON": -0.8
}


RADIUS_COLOR = {
    "FOOD": VEH_ALIVE,
    "POISON": VEH_DEAD
}


MUTATION_RATE = 0.1
MUTATION_IMPACT = 0.05

PADDING = 50
MENU_HEIGHT = 25
CALC_PER_FRAME = 1
FPS = 90
